{"name": "test_courier_login_no_data_fail[user_data3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (504 == 400)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <test_courier.TestCourierLoginAPI object at 0x000001FFE4A62F50>, user_data = {'login': 'test_login_1789'}\n\n    @allure.description('Проверяем попытку входа с отправкой недостаточных данных')\n    @pytest.mark.parametrize('user_data', (TestCourier.login_empty_login, TestCourier.login_empty_password, TestCourier.login_only_password, TestCourier.login_only_login))\n    def test_courier_login_no_data_fail(self, user_data):\n        r = requests.post(TestAPICourierLinks.main_url + TestAPICourierLinks.login_url, data=user_data)\n    \n>       assert r.status_code == 400 and r.json()['message'] == CourierErrors.error_login_no_data\nE       assert (504 == 400)\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_courier.py:57: AssertionError"}, "description": "Проверяем попытку входа с отправкой недостаточных данных", "parameters": [{"name": "user_data", "value": "{'login': 'test_login_1789'}"}], "start": 1699369265260, "stop": 1699369325319, "uuid": "94852bce-92e3-4d71-b93b-043eb621f75a", "historyId": "1d5dd992a78d294841385c37a294ee4f", "testCaseId": "9d10fbc3585789bb29ad092d3d064fa0", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "17436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}