{"name": "test_courier_login_no_such_user_fail", "status": "passed", "description": "Проверяем попытку входа с отправкой несуществующих данных", "start": 1699369350289, "stop": 1699369350377, "uuid": "0d4a1d90-3029-422b-b8ec-b7da3ac18cca", "historyId": "2a06b3c443fe2c81b22f6ddff3379aba", "testCaseId": "2a06b3c443fe2c81b22f6ddff3379aba", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_such_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "18296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}