{"name": "test_courier_login_no_such_user_fail", "status": "passed", "description": "Проверяем попытку входа с отправкой несуществующих данных", "start": 1699369264749, "stop": 1699369264835, "uuid": "1d5b27ae-3926-422c-8abb-5ec4d93fbfef", "historyId": "2a06b3c443fe2c81b22f6ddff3379aba", "testCaseId": "2a06b3c443fe2c81b22f6ddff3379aba", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_such_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "i101922157"}, {"name": "thread", "value": "17436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}